# Generated by Django 4.2.11 on 2024-12-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='specification',
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
