# Generated by Django 4.2.11 on 2024-12-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_image_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_url',
            new_name='image',
        ),
    ]
