# Generated by Django 4.2.11 on 2024-12-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_image_url_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
