# Generated by Django 4.2.11 on 2024-12-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
