# Generated by Django 4.2.11 on 2024-12-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_pricehistory_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='price_imgs/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_imgs', to='items.item')),
            ],
        ),
    ]
